// lib/constants.ts

export const events = [
    {
        id: "1",
        slug: "react-summit-2026",
        title: "React Summit 2026",
        date: "June 18, 2026",
        time: "10:00 AM",
        location: "Amsterdam, Netherlands",
        mode: "offline",
        attendees: 3200,
        price: "₹12,999",
        image: "/images/event1.png",
        description:
            "One of the world’s largest React conferences featuring expert talks, workshops, and networking.",
    },
    {
        id: "2",
        slug: "google-io-extended-delhi",
        title: "Google I/O Extended Delhi",
        date: "May 25, 2026",
        time: "11:30 AM",
        location: "New Delhi, India",
        mode: "offline",
        attendees: 850,
        price: "Free",
        image: "/images/event2.png",
        description:
            "Community-led Google I/O event covering Android, AI, Firebase, and Google Cloud.",
    },
    {
        id: "3",
        slug: "ethglobal-bangalore",
        title: "ETHGlobal Bangalore",
        date: "July 12, 2026",
        time: "9:00 AM",
        location: "Bangalore, India",
        mode: "offline",
        attendees: 1400,
        price: "₹1,499",
        image: "/images/event3.png",
        description:
            "Build Web3 projects alongside developers, founders, and mentors in a high-energy hackathon.",
    },
    {
        id: "4",
        slug: "aws-community-day-mumbai",
        title: "AWS Community Day Mumbai",
        date: "August 9, 2026",
        time: "1:00 PM",
        location: "Mumbai, India",
        mode: "offline",
        attendees: 1100,
        price: "₹2,999",
        image: "/images/event4.png",
        description:
            "Deep dives into AWS, DevOps, cloud architecture, and serverless systems.",
    },
    {
        id: "5",
        slug: "hackmit-2026",
        title: "HackMIT 2026",
        date: "September 21, 2026",
        time: "8:30 AM",
        location: "Cambridge, USA",
        mode: "offline",
        attendees: 1000,
        price: "Free",
        image: "/images/event5.png",
        description:
            "Prestigious student hackathon bringing together top builders for 24 hours of innovation.",
    },
    {
        id: "6",
        slug: "jsnation-live",
        title: "JSNation Live",
        date: "October 3, 2026",
        time: "10:30 AM",
        location: "Berlin, Germany",
        mode: "offline",
        attendees: 2600,
        price: "₹10,499",
        image: "/images/event6.png",
        description:
            "A premier JavaScript event focused on frontend, backend runtimes, tooling, and performance.",
    },
];